receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "temporal-demo-server"
          scrape_interval: 5s
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ["host.docker.internal:8090"]

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"   #  Makes the metrics available on the /metrics
#    namespace: "otel"   

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheus]