spring:
  application:
      name: "temporal-demo-ui"
        
  temporal:
    namespace: donald-demo.sdvdw
    workersAutoDiscovery:
      packages: 
        - com.donald.demo
    connection:
      target: donald-demo.sdvdw.tmprl.cloud:7233
      mtls:
        key-file: /Users/donald/stuff/source/certificates/temporal-client.key
        cert-chain-file: /Users/donald/stuff/source/certificates/temporal-client-leaf.pem

#  thymeleaf:
#      prefix: "classpath:/templates/"
#      suffix: ".html"
#      mode: HTML


management:
  endpoints:
    web:
      exposure:
        include: prometheus,temporalworkerinfo

demonstration:
    test: Hello
    demo:
        - name: Hello World
          link: hello-world
          description: Simple workflow to return a greeting.
        - name: Transfer Money
          link: money-transfer-welcome
          description: Demonstrate using Temporal to transfer money from one account to another.  Includes approval workflows, error handling, retries etc.
        - name: Temporal Cloud Namespace Management
          link: namespace-management
          description: Allows the user to view namespaces in the cloud and add/rotate certificates.

money-transfer:
    defaultAmount: 10 
    destinationAccounts:
        - firstName: Novak
          lastName: Djokovic
          sortCode: "73-23-88"
          accountId: "A72384720"
        - firstName: Dafne
          lastName: Schippers
          sortCode: "77-88-99"
          accountId: "ABC123001"
        - firstName: Sebastian
          lastName: Vettel
          sortCode: "75-23-88"
          accountId: "7238472W0"
        - firstName: Cristiano
          lastName: Ronaldo
          sortCode: "73-11-88"
          accountId: "00872E63"
    workflowOptions:
        - option: HAPPY_PATH
          optionDescription: Normal Happy-Path Execution
        - option: HUMAN_IN_LOOP
          optionDescription: Require Human-in-loop approval
        - option: API_DOWNTIME
          optionDescription: API Downtime (recover on 5th attempt)
        - option: BUG_IN_WORKFLOW
          optionDescription: Bug in workflow (Recoverable failure)
        - option: INVALID_ACCOUNT
          optionDescription: Invalid account selected (Unrecoverable failure)
        - option: FAIL_DEPOSIT
          optionDescription: Deposit Failure (Unrecoverable failure)

cloud-operations-service:
  host: localhost
  port: 8091
  protocol: http

cloud-operations-regions:
  regions:
    - aws-ap-northeast-1
    - aws-ap-norteast-2
    - aws-ap-south-1
    - aws-ap-southeast-1
    - aws-ap-southeast-2
    - aws-ca-central-1
    - aws-eu-central-1
    - aws-eu-west-1
    - aws-eu-west-2
    - aws-us-east-1
    - aws-us-east-2
    - aws-us-west-2
    - gcp-us-central1
